# Generated by Django 5.0.6 on 2024-07-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_orderitem_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
