# Generated by Django 5.0.6 on 2024-06-30 13:01

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=124)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category')),
            ],
            options={
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=248)),
                ('slug', models.SlugField(max_length=264, unique=True)),
                ('brand', models.CharField(max_length=248)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=99.99, max_digits=7)),
                ('image', models.ImageField(upload_to='products/products/%Y/%m/%d')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
            managers=[
                ('available', django.db.models.manager.Manager()),
            ],
        ),
    ]
